name: CI - Lint Python and Markdown

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-python:
    runs-on: ubuntu-latest
    name: Lint Python Scripts
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install flake8
        run: pip install flake8
      - name: Lint scripts/
        run: flake8 scripts/

  lint-markdown:
    runs-on: ubuntu-latest
    name: Lint Markdown Files
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install markdownlint-cli
        run: npm install -g markdownlint-cli
      - name: Lint Markdown files
        run: markdownlint '**/*.md'
